---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-pocket-id
  namespace: security
spec:
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        DB_CONNECTION_STRING: |-
          postgresql://{{ .PG_USER }}:{{ .PG_PASS }}@postgres-lb.database.svc.cluster.local/pocket-id
        INIT_POSTGRES_DBNAME: pocket-id
        INIT_POSTGRES_HOST: postgres-lb.database.svc
        INIT_POSTGRES_USER: |-
          {{ .PG_USER }}
        INIT_POSTGRES_PASS: |-
          {{ .PG_PASS }}
        INIT_POSTGRES_SUPER_PASS: |-
          {{ .password }}
  refreshInterval: 15m
  dataFrom:
    - extract:
        key: pocket-id
    - extract:
        key: postgres