---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pocket-id
  namespace: default
spec:
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    deletionPolicy: Delete
    name: pocket-id-secret
    template:
      type: Opaque
      data:
        DB_CONNECTION_STRING: |-
          postgresql://{{ .PG_USER }}:{{ .PG_PASS }}@postgres18-rw.database.svc.cluster.local/pocket-id
        INIT_POSTGRES_DBNAME: pocket-id
        INIT_POSTGRES_HOST: postgres18-rw.database.svc
        INIT_POSTGRES_USER: |-
          {{ .PG_USER }}
        INIT_POSTGRES_PASS: |-
          {{ .PG_PASS }}
        INIT_POSTGRES_SUPER_PASS: |-
          {{ .ROOT_PASS }}
  refreshInterval: 1h
  dataFrom:
    - extract:
        key: pocket-id
    - extract:
        key: cloudnative-pg