---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: porkboi-io
spec:
  dnsNames:
    - porkboi.io
    - "*.porkboi.io"
  duration: 160h
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  secretName: porkboi-io-tls
  usages:
    - digital signature