apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: argocd
spec:
  syncPolicy:
    applicationsSync: create-only
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: &repoURL https://github.com/jimmy-ungerman/pork3s
        revision: &revision main
        directories:
          - path: kubernetes/porkos/apps/database/*
          - path: kubernetes/porkos/apps/default/*
          - path: kubernetes/porkos/apps/kube-system/*
          - path: kubernetes/porkos/apps/observability/*
          - path: kubernetes/porkos/apps/system/*
          - path: kubernetes/porkos/apps/volsync-system
  template:
    metadata:
      name: '{{.path.basename}}'
      annotations:
        argocd.argoproj.io/sync-wave: '4'
    spec:
      destination:
        name: in-cluster
        namespace: '{{ (split "/" .path.path)._3 }}'
      project: default
      source:
        repoURL: *repoURL
        path: '{{.path.path}}'
        targetRevision: *revision
      syncPolicy:
        automated: {}
        retry:
          limit: 10
          backoff:
            duration: 1m
            factor: 2
            maxDuration: 16m
        syncOptions:
          - CreateNamespace=true
          - RespectIgnoreDifferences=true
          - ServerSideApply=true
          - Validate=false