---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
components:
  - ../../components/alerts
resources:
  - ./namespace.yaml
  - ./actual/ks.yaml
  - ./agregarr/ks.yaml
  - ./bazarr/ks.yaml
  - ./home-assistant/ks.yaml
  - ./karakeep/ks.yaml
  - ./matter-server/ks.yaml
  - ./mosquitto/ks.yaml
  - ./plex/ks.yaml
  - ./prowlarr/ks.yaml
  - ./radarr/ks.yaml
  - ./recyclarr/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./seerr/ks.yaml
  - ./sonarr/ks.yaml
  - ./zigbee/ks.yaml
  - ./staubscraper/ks.yaml
