apiVersion: v2
name: rook-ceph
version: 0.0.0
dependencies:
  - name: rook-ceph
    version: v1.16.5
    repository: https://charts.rook.io/release
    alias: operator
  - name: rook-ceph-cluster
    version: v1.16.5
    repository: https://charts.rook.io/release